[package]
name = "tgbot-manager"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
env_logger = "0.9.0"
log = "0.4.17"
teloxide = { version = "0.10.1", features = ["full"] }
tokio = { version = "1", features = ["full"] }
