[package]
name = "tgbot-nochanmsg"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
teloxide = { version = "0.5", features = ["full"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
